---
- name: 'restart-docker-php'
  become: yes
  docker_container:
    image: "php:{{ php_docker_tag }}"
    name: "{{ php_container_name }}"
    ports: '{{ php_published_ports }}'
    expose: '{{ php_exposed_ports }}'
    state: 'stopped'
    restart_policy: 'always'
    log_driver: 'syslog'
    log_opt:
      tag: "{{ php_container_name }}"
  notify: 'start-docker-php'

- name: 'start-docker-php'
  become: yes
  docker_container:
    image: "php:{{ php_docker_tag }}"
    name: "{{ php_container_name }}"
    ports: '{{ php_published_ports }}'
    expose: '{{ php_exposed_ports }}'
    state: 'started'
    restart_policy: 'always'
    log_driver: 'syslog'
    log_opt:
      tag: "{{ php_container_name }}"